# Generated by Django 4.0.1 on 2022-02-15 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_rename_account_calc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calc',
            name='birthday',
            field=models.DateField(),
        ),
    ]
